### PR TITLE
[#124] Added support for async rest template

### LINKED ISSUE #124: Support AsyncRestTemplate
It appears there is no support for `AsyncRestTemplate`. Sleuth has no way of intercepting the client's async requests to inject the corresponding headers. Therefore, it sends the requests without them. And of course, the responses do not carry them either and as a consequence Sleuth cannot propagate those headers into the thread running the ListenableFuture's callback.

I am using a sample project to demonstrate it : https://github.com/pivotalcsoemea/distributed-tracing-demo/blob/master/gateway/src/main/java/io/pivotal/demo/gateway/AsyncController.java#L51

I have noticed that when the inner Restful request (https://github.com/pivotalcsoemea/distributed-tracing-demo/blob/master/gateway/src/main/java/io/pivotal/demo/gateway/AsyncController.java#L72) is invoked, Sleuth logs the following statement (I have included the two previous statements for reference):

```
2016-01-20 18:38:00.464  INFO 97307 --- [nio-8080-exec-1] io.pivotal.demo.gateway.AsyncController  : Opening trade bob 100.0 @ 07d05a11-9483-4481-8876-70fb5ccc98e8

2016-01-20 18:38:00.799  WARN 97307 --- [/O dispatcher 1] io.pivotal.demo.gateway.AsyncController  : No Span avaliable in applySpread method

2016-01-20 18:38:00.820  WARN 97307 --- [nio-8080-exec-2] o.s.cloud.sleuth.util.ExceptionUtils     : Trace client warn: thread http-nio-8080-exec-2 tried to start a new Span with parent MilliSpan(begin=1453311480819, end=0, name=null, traceId=07d05a11-9483-4481-8876-70fb5ccc98e8, parents=[], spanId=07d05a11-9483-4481-8876-70fb5ccc98e8, remote=true, exportable=true, annotations={}, processId=null, timelineAnnotations=[]), but there is already a currentSpan MilliSpan(begin=1453311480404, end=0, name=http/async/open, traceId=07d05a11-9483-4481-8876-70fb5ccc98e8, parents=[], spanId=07d05a11-9483-4481-8876-70fb5ccc98e8, remote=false, exportable=false, annotations={account=bob}, processId=null, timelineAnnotations=[])
```

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
fixes #124

CC @dsyer , @spencergibb , @adriancole

### CODE REVIEW

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceAsyncClientHttpRequestFactoryWrapper.java [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+ * @see SpanAccessor
+ *
+ * @author Marcin Grzejszczak
+ * @author Spencer Gibb
+ */
+public class TraceAsyncClientHttpRequestFactoryWrapper extends AbstractTraceHttpRequestInterceptor
+		implements AsyncClientHttpRequestFactory {
+
+	private ApplicationEventPublisher publisher;
+	private final AsyncClientHttpRequestFactory delegate;
```
Comment (spencergibb) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceAsyncClientHttpRequestFactoryWrapper.java]: Clever to wrap it with a delegate. We don't even have support for a loadbalanced `AsyncRestTemplate`. This could be a way to do that.

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+		setHeader(request, Span.SPAN_NAME_NAME, span.getName().toString());
+		setHeader(request, Span.PARENT_ID_NAME, getParentId(span));
+		setHeader(request, Span.PROCESS_ID_NAME, span.getProcessId());
+	}
+
+	private Long getParentId(Span span) {
+		return !span.getParents().isEmpty() ? span.getParents().get(0) : null;
+	}
+
+	public void setHeader(HttpRequest request, String name, String value) {
```
Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java]: nit addHeader

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+	public void setHeader(HttpRequest request, String name, Long value) {
+		if (value != null) {
+			setHeader(request, name, Span.toHex(value));
+		}
+	}
+
+	/**
+	 * Close the current span and emit the ClientReceivedEvent
+	 */
+	public void close() {
```
Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java]: in opentracing, this is finish()

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+		publish(new ClientReceivedEvent(this, getCurrentSpan()));
+	}
+
+	protected void publish(ApplicationEvent event) {
+		if (this.publisher != null) {
+			this.publisher.publishEvent(event);
+		}
+	}
+
+	protected Span getCurrentSpan() {
```
Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java]: I usually don't add get prefix unless there's a setter

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java (hunk 2 above)
Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java]: oh I see, we are conditionally setting (vs adding a second header) nm

Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java]: pls add javadoc for public non-internal symbols (ps this encourages less visibility :P)

Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java]: ex javadoc public symbols only when non-obvious. for example, it isn't obvious what's going on until you read the code... this one is a bit hard to document as it is weird..

```
/** Adds the header if not already present and we're tracing. */
```

ps this is racy so I assume we'd document the type as not thread-safe.

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+ *
+ * @author Marcin Grzejszczak
+ */
+public abstract class AbstractTraceHttpRequestInterceptor
+		implements ApplicationEventPublisherAware {
+
+	private ApplicationEventPublisher publisher;
+	private final SpanAccessor accessor;
+
+	public AbstractTraceHttpRequestInterceptor(SpanAccessor accessor) {
```
Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java]: nit protected

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java [hunk 6]
```diff
@@ -0,0 +1,99 @@
...
+
+	@Override
+	public void setApplicationEventPublisher(ApplicationEventPublisher publisher) {
+		this.publisher = publisher;
+	}
+
+	/**
+	 * Adds trace related headers from the span to the request
+	 */
+	public void enrichWithTraceHeaders(HttpRequest request, Span span) {
```
Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java]: should this be public?

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java [hunk 7]
```diff
@@ -0,0 +1,99 @@
...
+		this.accessor = accessor;
+	}
+
+	@Override
+	public void setApplicationEventPublisher(ApplicationEventPublisher publisher) {
+		this.publisher = publisher;
+	}
+
+	/**
+	 * Adds trace related headers from the span to the request
```
Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java]: maybe change this to say what to do? guess below

```java
/**
 * Implementations must call this only once, after creating the span, but before publishing events.
 */
```

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java [hunk 8]
```diff
@@ -0,0 +1,99 @@
...
+		return !span.getParents().isEmpty() ? span.getParents().get(0) : null;
+	}
+
+	public void setHeader(HttpRequest request, String name, String value) {
+		if (StringUtils.hasText(value) && !request.getHeaders().containsKey(name) && this.accessor.isTracing()) {
+			request.getHeaders().add(name, value);
+		}
+	}
+
+	public void setHeader(HttpRequest request, String name, Long value) {
```
Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java]: maybe setIdHeader?

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceAsyncClientHttpRequestFactoryWrapper.java [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+	public AsyncClientHttpRequest createAsyncRequest(URI uri, HttpMethod httpMethod)
+			throws IOException {
+		AsyncClientHttpRequest request = this.delegate.createAsyncRequest(uri, httpMethod);
+		Span span = getCurrentSpan();
+		if (span == null) {
+			setHeader(request, Span.NOT_SAMPLED_NAME, "true");
+			return request;
+		}
+		enrichWithTraceHeaders(request, span);
+		publish(new ClientSentEvent(this, span));
```
Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceAsyncClientHttpRequestFactoryWrapper.java]: I'd kill enrichWithTraceHeaders and instead make publishStartEvent. This makes it more obvious what you are hoping people do

**Comment by adriancole** [comment]
One one hand, it is preventing copy/paste of code, but on the other hand, it is adding another type which will need refactoring: `AbstractTraceHttpRequestInterceptor`. If there's any way to hide this type, please do.
