### PR TITLE
fix #2023, add parent in the new TraceFeignContext

### LINKED ISSUE #2023: Enable refresh in spring-cloud-openfeign would cause initialization failure
While enable refresh in spring-cloud-openfeign: `feign.client.refresh-enabled=true`, the initialization would be failed and got exception like:

```
org.springframework.beans.factory.BeanCreationException: Could not inject field: private com.github.jojotech.spring.cloud.webmvc.test.feign.OpenFeignClientTest$TestService1Client com.github.jojotech.spring.cloud.webmvc.test.feign.OpenFeignClientTest.testService1Client; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.github.jojotech.spring.cloud.webmvc.test.feign.OpenFeignClientTest$TestService1Client': Unexpected exception during bean creation; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'feign.Request.Options-testService1Client' available
```

### PR DESCRIPTION
**Pull request by HashZhang**
as stated in title

### CODE REVIEW

File: spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessor.java [hunk 1]
```diff
@@ -43,7 +61,14 @@ public Object postProcessBeforeInitialization(Object bean, String beanName) thro
 	@Override
 	public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
 		if (bean instanceof FeignContext && !(bean instanceof TraceFeignContext)) {
-			return new TraceFeignContext(traceFeignObjectWrapper(), (FeignContext) bean);
+			FeignContext feignContext = (FeignContext) bean;
+			TraceFeignContext traceFeignContext = new TraceFeignContext(traceFeignObjectWrapper(), feignContext);
+			try {
+				traceFeignContext.setApplicationContext((ApplicationContext) PARENT.get(bean));
```
Comment (marcingrzejszczak) [inline spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessor.java:67]: Why not change the `FeignContext` to have a getter for the application context and then we would get rid of the reflection approach?

**Comment by marcingrzejszczak** [comment]
Thanks for the PR! Can you please add tests and look at my comment ?

File: spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessor.java (hunk 1 above)
Comment (HashZhang) [reply spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessor.java:67]: That's better, will be changed

**Comment by marcingrzejszczak** [comment]
Hey, I've merged the commons fix. Can you please update the code to reflect this?

**Comment by HashZhang** [comment]
Noted. Will be done

File: spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessor.java [hunk 2]
```diff
@@ -43,7 +43,10 @@ public Object postProcessBeforeInitialization(Object bean, String beanName) thro
 	@Override
 	public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
 		if (bean instanceof FeignContext && !(bean instanceof TraceFeignContext)) {
-			return new TraceFeignContext(traceFeignObjectWrapper(), (FeignContext) bean);
+			FeignContext feignContext = (FeignContext) bean;
+			TraceFeignContext traceFeignContext = new TraceFeignContext(traceFeignObjectWrapper(), feignContext);
+			traceFeignContext.setApplicationContext(bean.getParent());
```
Comment (marcingrzejszczak) [inline spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessor.java:48]: > 			traceFeignContext.setApplicationContext(bean.getParent());

shouldn't this be 

```
			traceFeignContext.setApplicationContext(feignContext.getParent());
```

**Review by marcingrzejszczak — CHANGES_REQUESTED** [review]
Also please add tests

File: spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessor.java (hunk 2 above)
Comment (HashZhang) [reply spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessor.java]: sorry for the mistake

File: spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java [hunk 3]
```diff
@@ -0,0 +1,21 @@
+package org.springframework.cloud.sleuth.instrument.web.client.feign;
```
Comment (marcingrzejszczak) [inline spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java:1]: You need the copyright header here

File: spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+
+    @Test
+    void should_have_parent_after_post_processed() {
+        FeignContextBeanPostProcessor feignContextBeanPostProcessor = new FeignContextBeanPostProcessor(Mockito.mock(BeanFactory.class));
+        FeignContext feignContext = new FeignContext();
+        feignContext.setApplicationContext(Mockito.mock(ApplicationContext.class));
+        TraceFeignContext traceFeignContext = (TraceFeignContext) feignContextBeanPostProcessor.postProcessAfterInitialization(feignContext, "test");
+        Assertions.assertNotNull(traceFeignContext.getParent());
+    }
+}
```
Comment (marcingrzejszczak) [inline spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java:21]: A new line is needed here

File: spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+
+class FeignContextBeanPostProcessorTest {
+
+    @Test
+    void should_have_parent_after_post_processed() {
+        FeignContextBeanPostProcessor feignContextBeanPostProcessor = new FeignContextBeanPostProcessor(Mockito.mock(BeanFactory.class));
+        FeignContext feignContext = new FeignContext();
+        feignContext.setApplicationContext(Mockito.mock(ApplicationContext.class));
+        TraceFeignContext traceFeignContext = (TraceFeignContext) feignContextBeanPostProcessor.postProcessAfterInitialization(feignContext, "test");
+        Assertions.assertNotNull(traceFeignContext.getParent());
```
Comment (marcingrzejszczak) [inline spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java:19]: Please use assertj assertions instead of junit ones. Also I understand that we expect the parent to be same as the one from line 17, right? Maybe we should assert on that?

File: spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java [hunk 6]
```diff
@@ -0,0 +1,21 @@
...
+
+
+class FeignContextBeanPostProcessorTest {
+
+    @Test
+    void should_have_parent_after_post_processed() {
+        FeignContextBeanPostProcessor feignContextBeanPostProcessor = new FeignContextBeanPostProcessor(Mockito.mock(BeanFactory.class));
+        FeignContext feignContext = new FeignContext();
+        feignContext.setApplicationContext(Mockito.mock(ApplicationContext.class));
+        TraceFeignContext traceFeignContext = (TraceFeignContext) feignContextBeanPostProcessor.postProcessAfterInitialization(feignContext, "test");
```
Comment (marcingrzejszczak) [inline spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java:18]: Can you put this in a separate line to separate given when and then sections?

File: spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java [hunk 7]
```diff
@@ -0,0 +1,21 @@
...
+import org.mockito.Mockito;
+import org.springframework.beans.factory.BeanFactory;
+import org.springframework.cloud.openfeign.FeignContext;
+import org.springframework.context.ApplicationContext;
+
+
+class FeignContextBeanPostProcessorTest {
+
+    @Test
+    void should_have_parent_after_post_processed() {
```
Comment (marcingrzejszczak) [inline spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java:14]: the test name should be something like `should_pass_feign_application_context_to_the_trace_representation()`

File: spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java [hunk 8]
```diff
@@ -0,0 +1,21 @@
...
+
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+import org.mockito.Mockito;
+import org.springframework.beans.factory.BeanFactory;
+import org.springframework.cloud.openfeign.FeignContext;
+import org.springframework.context.ApplicationContext;
+
+
+class FeignContextBeanPostProcessorTest {
```
Comment (marcingrzejszczak) [inline spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessorTest.java:11]: If you want to you can leverage `MockitoExtensions` and inject `@Mock` into fields. There are other examples out there in the repo.

**Review by marcingrzejszczak — CHANGES_REQUESTED** [review]

**Comment by marcingrzejszczak** [comment]
Congrats @HashZhang on your contribution :)
