### PR TITLE
Get KafkaStreamsTracing via BeanFactory to prevent eager initialization

### LINKED ISSUE #1599: sleuth triggering early init of beans ?
It seems that under certain scenario's, sleuth triggers a cascade of early bean initialization which brakes things. I have isolated a testcase here https://github.com/jorgheymans/sleuth-bug . If you run it you'll see the `BeanPostProcessorChecker` emitting lots of these:

```
2020-04-04 09:06:50.714  INFO [,,,] 13242 --- [           main] sleuthbug.Application                    : No active profile set, falling back to default profiles: default
2020-04-04 09:06:51.087  INFO [,,,] 13242 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=6f243840-0f76-37dc-89e9-831761795ee8
2020-04-04 09:06:51.218  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.sleuth-org.springframework.cloud.sleuth.autoconfig.SleuthProperties' of type [org.springframework.cloud.sleuth.autoconfig.SleuthProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.221  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.sleuth.propagation.tag-org.springframework.cloud.sleuth.propagation.SleuthTagPropagationProperties' of type [org.springframework.cloud.sleuth.propagation.SleuthTagPropagationProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.223  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'sleuthFinishedSpanHandler' of type [org.springframework.cloud.sleuth.propagation.TagPropagationFinishedSpanHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.227  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.sleuth.log.slf4j-org.springframework.cloud.sleuth.log.SleuthSlf4jProperties' of type [org.springframework.cloud.sleuth.log.SleuthSlf4jProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.229  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'slf4jSpanDecorator' of type [org.springframework.cloud.sleuth.log.Slf4jScopeDecorator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.233  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.sleuth.autoconfig.TraceAutoConfiguration' of type [org.springframework.cloud.sleuth.autoconfig.TraceAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.238  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'sleuthPropagation' of type [brave.propagation.B3Propagation$Factory] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.241  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'sleuthCurrentTraceContextBuilder' of type [brave.propagation.ThreadLocalCurrentTraceContext$Builder] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.243  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'sleuthCurrentTraceContext' of type [brave.propagation.ThreadLocalCurrentTraceContext] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.283  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'errorParser' of type [brave.ErrorParser] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.286  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.sleuth.zipkin2.ZipkinAutoConfiguration' of type [org.springframework.cloud.sleuth.zipkin2.ZipkinAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.288  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.sleuth.autoconfig.TraceAutoConfiguration$TraceMetricsInMemoryConfiguration' of type [org.springframework.cloud.sleuth.autoconfig.TraceAutoConfiguration$TraceMetricsInMemoryConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.289  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'sleuthReporterMetrics' of type [zipkin2.reporter.InMemoryReporterMetrics] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.297  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.zipkin-org.springframework.cloud.sleuth.zipkin2.ZipkinProperties' of type [org.springframework.cloud.sleuth.zipkin2.ZipkinProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.302  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateSenderConfiguration$DiscoveryClientZipkinUrlExtractorConfiguration$ZipkinClientLoadBalancedConfiguration' of type [org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateSenderConfiguration$DiscoveryClientZipkinUrlExtractorConfiguration$ZipkinClientLoadBalancedConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.306  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'loadBalancerClientZipkinLoadBalancer' of type [org.springframework.cloud.sleuth.zipkin2.sender.LoadBalancerClientZipkinLoadBalancer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.309  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'zipkinUrlExtractor' of type [org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateSenderConfiguration$CachingZipkinUrlExtractor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.311  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateSenderConfiguration' of type [org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateSenderConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.313  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'zipkinRestTemplateCustomizer' of type [org.springframework.cloud.sleuth.zipkin2.DefaultZipkinRestTemplateCustomizer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.322  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'zipkinSender' of type [org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.367  WARN [,,,] 13242 --- [           main] o.s.c.s.zipkin2.ZipkinAutoConfiguration  : Check result of the [AsyncReporter{org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender@2881ad47}] contains an error [CheckResult{ok=false, error=org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9411/api/v2/spans": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)}]
2020-04-04 09:06:51.368  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'zipkinReporter' of type [zipkin2.reporter.AsyncReporter$BoundedAsyncReporter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.379  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'tracing' of type [brave.Tracing$Default] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.390  INFO [,,,] 13242 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'kafkaStreamsTracing' of type [brave.kafka.streams.KafkaStreamsTracing] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-04 09:06:51.746  INFO [,,,] 13242 --- [           main] sleuthbug.Application                    : Started Application in 1.581 seconds (JVM running for 2.624)
```

When starting with `--spring.sleuth.messaging.kafka.streams.enabled=false` , you will see that all of these warnings disappear.

Now i know that early bean instantiation is not always an issue, but for our app it is because we can for example see that our PrometheusMetrics are incomplete, many metrics are missing that reappear when we disable above flag. There may be other side effects not so apparent.

### PR DESCRIPTION
**Pull request by timtebeek**
Fixes #1599 

Had to wrestle a bit with the [sample project added by @jorgheymans](https://github.com/jorgheymans/sleuth-bug) by using `spring-cloud-dependencies:Hoxton.SR4` as parent adding the following two properties:
```
<brave.version>5.11.2</brave.version>
<spring-cloud-sleuth.version>2.2.3.BUILD-SNAPSHOT</spring-cloud-sleuth.version>
```
But after that, and with the changes on this PR cherry-picked into the Sleuth `2.2.x`  branch, I no longer see the message when starting that application. @jorgheymans can you confirm?

Not entirely sure if/how I could add a unit test to prove this works otherwise.

### CODE REVIEW

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/SleuthKafkaStreamsConfiguration.java [hunk 1]
```diff
@@ -66,8 +67,8 @@ static KafkaStreamsTracing kafkaStreamsTracing(Tracing tracing) {
 
 	@Bean
 	static KafkaStreamsBuilderFactoryBeanPostProcessor kafkaStreamsBuilderFactoryBeanPostProcessor(
-			KafkaStreamsTracing kafkaStreamsTracing) {
-		return new KafkaStreamsBuilderFactoryBeanPostProcessor(kafkaStreamsTracing);
+			BeanFactory beanFactory) {
```
Comment (spencergibb) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/SleuthKafkaStreamsConfiguration.java:70]: Maybe `ObjectProvider<KafkaStreamsTracing>` so the type is not lost.

Comment (timtebeek) [reply spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/SleuthKafkaStreamsConfiguration.java]: Good suggestion, thanks! Applied just now.

**Comment by jorgheymans** [comment]
@timtebeek thanks for this, i'm happy to test are there any snapshot builds available ? But if you say it works on my repro case then i'm pretty confident it will work for my application as well as it's literally a trimmed down version until the bare minimum to show the bug.

**Comment by timtebeek** [comment]
@jorgheymans Thanks for the quick reply and offer to test; I've (now) also forked your sample project so there are these two branches you can test together:
https://github.com/jorgheymans/sleuth-bug/compare/master...timtebeek:2.2.x
https://github.com/spring-cloud/spring-cloud-sleuth/compare/2.2.x...timtebeek:2.2.x

The changes in the pull request are on sleuth master, targeting a future 3.0.0 release for Spring Boot 2.3. The second link above can be used if we want to backport this fix to 2.2.x in Sleuth.

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/SleuthKafkaStreamsConfiguration.java [hunk 2]
```diff
@@ -66,8 +67,8 @@ static KafkaStreamsTracing kafkaStreamsTracing(Tracing tracing) {
 
 	@Bean
 	static KafkaStreamsBuilderFactoryBeanPostProcessor kafkaStreamsBuilderFactoryBeanPostProcessor(
-			KafkaStreamsTracing kafkaStreamsTracing) {
-		return new KafkaStreamsBuilderFactoryBeanPostProcessor(kafkaStreamsTracing);
+			ObjectProvider<KafkaStreamsTracing> objectProvider) {
```
Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/SleuthKafkaStreamsConfiguration.java:70]: I think this method deserves a comment about why ObjectProvider is needed (not saying it is wrong)

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/SleuthKafkaStreamsConfiguration.java [hunk 3]
```diff
@@ -86,22 +87,21 @@ static KafkaStreamsBuilderFactoryBeanPostProcessor kafkaStreamsBuilderFactoryBea
...
+	KafkaStreamsBuilderFactoryBeanPostProcessor(ObjectProvider<KafkaStreamsTracing> objectProvider) {
+		this.objectProvider = objectProvider;
 	}
 
 	@Override
 	public Object postProcessAfterInitialization(Object bean, String beanName)
 			throws BeansException {
 		if (bean instanceof StreamsBuilderFactoryBean) {
-			StreamsBuilderFactoryBean sbfb = (StreamsBuilderFactoryBean) bean;
+			KafkaStreamsTracing kafkaStreamsTracing = this.objectProvider.getIfAvailable();
```
Comment (adriancole) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/SleuthKafkaStreamsConfiguration.java:100]: this returns null, so probably deserves an if statement if no other reason clarity?

**Comment by timtebeek** [comment]
> It would be nice to create an eager initialization scenario in the test, but appreciate if you can't muster that.

Using @jorgheymans sample application I've added a test in https://github.com/spring-cloud/spring-cloud-sleuth/pull/1623/commits/56b44228da9965d3a1b859aea33c7b85e39f962c ; It's a bit involved as I knew of no other way to verify apart from `OutputCapture`, but it seems to work. If you revert the SleuthKafkaStreamsConfiguration on this branch before running the tests, they will fail. :)

**Comment by adriancole** [comment]
usually we merge to stable (currently 2.2.x) and merge back to master... something I've done opposite countless times.. I don't mind reversing this post merge. thanks for all the help!

**Comment by timtebeek** [comment]
Glad to help! Thanks for the quick review & merge!

**Comment by jeqo** [comment]
LGTM :) well done!

**Comment by marcingrzejszczak** [comment]
Great work! Thanks for helping us out :)
