### PR TITLE
Only wrap executors when context is refreshed

### LINKED ISSUE #1128: Deadlock with spring.data.jpa.repositories.bootstrap-mode=deferred
Spring Boot 2.1.0.RELEASE
Spring Cloud Greenwich.M1 (also Finchley.SR2)

Create a project with both spring-boot-starter-data-jpa and spring-cloud-starter-zipkin.
Set the new `spring.data.jpa.repositories.bootstrap-mode=deferred`.
Deadlock during startup.

Created minimal sample as a mashup of spring initialir with jpa and zipkin together with a simple entity and repository.

Steps to reproduce:
Unpack attached project.
Run "mvn clean test"

Remove the `spring.data.jpa.repositories.bootstrap-mode=deferred` line in application.properties and rerun to see test completing with sleuth.

Keep the property and remove the spring-cloud.-starter-zipkin dependency in the pom to see test completing without sleuth.

Main thread locks in `LocalContainerEntityManagerFactoryBean(AbstractEntityManagerFactoryBean).getNativeEntityManagerFactory() line: 539 [return this.nativeEntityManagerFactoryFuture.get();]`

JPA setup thread locks in `DefaultListableBeanFactory(DefaultSingletonBeanRegistry).getSingleton(String, boolean) line: 179 [synchronized (this.singletonObjects) { ]`

JPA setup thread stack:
```Thread [task-1] (Suspended)	
	waiting for: ConcurrentHashMap<K,V>  (id=84)	
	DefaultListableBeanFactory(DefaultSingletonBeanRegistry).getSingleton(String, boolean) line: 179	
	DefaultListableBeanFactory(AbstractBeanFactory).isTypeMatch(String, ResolvableType) line: 493	
	DefaultListableBeanFactory.doGetBeanNamesForType(ResolvableType, boolean, boolean) line: 514	
	DefaultListableBeanFactory.getBeanNamesForType(Class<?>, boolean, boolean) line: 485	
	DefaultListableBeanFactory.getBeanNamesForType(ResolvableType) line: 462	
	DefaultListableBeanFactory.resolveNamedBean(ResolvableType, Object[], boolean) line: 1098	
	DefaultListableBeanFactory.resolveBean(ResolvableType, Object[], boolean) line: 407	
	DefaultListableBeanFactory.getBean(Class<T>, Object...) line: 341	
	DefaultListableBeanFactory.getBean(Class<T>) line: 335	
	LazyTraceThreadPoolTaskExecutor.tracing() line: 231	
	LazyTraceThreadPoolTaskExecutor.execute(Runnable) line: 60	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 498	
	ExecutorBeanPostProcessor$1(ExecutorMethodInterceptor<T>).invoke(MethodInvocation) line: 148	
	CglibAopProxy$CglibMethodInvocation(ReflectiveMethodInvocation).proceed() line: 186	
	CglibAopProxy$DynamicAdvisedInterceptor.intercept(Object, Method, Object[], MethodProxy) line: 688	
	ThreadPoolTaskExecutor$$EnhancerBySpringCGLIB$$a86302b9.execute(Runnable) line: not available	
	DataSourceInitializedPublisher$DataSourceSchemaCreatedPublisher.postProcessEntityManagerFactory(EntityManagerFactory) line: 201	
	LocalContainerEntityManagerFactoryBean(AbstractEntityManagerFactoryBean).buildNativeEntityManagerFactory() line: 411	
	1974379194.call() line: not available	
	TraceCallable<V>.call() line: 63	
	FutureTask<V>.run() line: 266	
	ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1149	
	ThreadPoolExecutor$Worker.run() line: 624	
	Thread.run() line: 748	
```
[deferred.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2557728/deferred.zip)

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
without this change, for deferred JPA bootstrap, we're trying to get a bean very early and we have a deadlock
with this change, we only do it once the context is refreshed

the concept was such that I have a bean `ContextRefreshedListener` which is also an `AtomicBoolean`. Now, before we wrap any executor related logic, we use the `ContextUtil` to verify if the context is in the creation or not. There, we retrieve the `ContextRefreshedListener` bean and cache it. Only after `ContextRefreshedEvent` was received, will we start wrapping the executor services.

fixes #1128

### CODE REVIEW

File: spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ContextRefreshedListener.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+
+package org.springframework.cloud.sleuth.instrument.async;
+
+import java.util.concurrent.atomic.AtomicBoolean;
+
+import org.springframework.context.ApplicationListener;
+import org.springframework.context.event.ContextRefreshedEvent;
+
+class ContextRefreshedListener extends AtomicBoolean
+		implements ApplicationListener<ContextRefreshedEvent> {
```
Comment (dsyer) [inline spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ContextRefreshedListener.java]: It's better (faster) to use `SmartApplicationListener`. More code to write but less computation at runtime.
