### PR TITLE
Fix not able to override datasource-proxy log-level

### LINKED ISSUE #1973: datasource-proxy log level is always DEBUG, despite setting property to INFO
I'm using 2021.0.0-SNAPSHOT to get datasource-proxy functionality.

I'm setting the property spring.sleuth.jdbc.datasource-proxy.query.log-level to INFO and I get nothing in my log.

Added a breakpoint here DataSourceProxyBuilderCustomizer#customize(ProxyDataSourceBuilder proxyDataSourceBuilder

and it seems that the result of this.datasourceProxy.getQuery().getLogLevel() is always DEBUG , regardless of what you set it the the property to.

Tried the same datasource-proxy scenario via datasource-proxy-spring-boot-starter 1.7.1 and it works fine.

Please let me know if I can provide any further information

### PR DESCRIPTION
**Pull request by beatfreaker**
Fixes #1973 

@marcingrzejszczak @gavlyukovskiy can you please review this PR

- Aligned default values of `Query` & `SlowQuery` in `TraceJdbcProperties.DataSourceProxyProperties` and `DataSourceProxyProperties`
- Add code to copy properties of `Query` and `SlowQuery` in `DataSourceProxyConfiguration`
- Add test case to check if `log-level` can be overridden or not

### CODE REVIEW

File: spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/TraceJdbcProperties.java [hunk 1]
```diff
@@ -190,7 +190,7 @@ public void setJsonFormat(boolean jsonFormat) {
 			/**
 			 * Enable logging all queries to the log.
 			 */
-			private boolean enableLogging = false;
+			private boolean enableLogging = true;
```
Comment (marcingrzejszczak) [inline spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/TraceJdbcProperties.java:193]: We had a chat with @gavlyukovskiy that having this turned on by default can lead to gigantic amount of logs. I'd leave both as opt in.

File: spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/DataSourceProxyConfiguration.java [hunk 2]
```diff
@@ -84,6 +84,8 @@ private DataSourceProxyProperties props(TraceJdbcProperties traceJdbcProperties)
 		DataSourceProxyProperties props = new DataSourceProxyProperties();
 		BeanUtils.copyProperties(originalProxy, props);
 		props.setLogging(DataSourceProxyProperties.DataSourceProxyLogging.valueOf(originalProxy.getLogging().name()));
+		BeanUtils.copyProperties(originalProxy.getQuery(), props.getQuery());
```
Comment (marcingrzejszczak) [inline spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/DataSourceProxyConfiguration.java:87]: :grimacing: oops

**Review by marcingrzejszczak — CHANGES_REQUESTED** [review]
Thanks for catching my mistakes :facepalm:

File: spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/TraceJdbcProperties.java (hunk 1 above)
Comment (beatfreaker) [reply spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/TraceJdbcProperties.java:193]: So in that case we should set this [DataSourceProxyProperties.java#L116](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/DataSourceProxyProperties.java#L116) to `false` too, because at the end we are using this property class to build `ProxyDataSource`.

Also, if we set it to `false`, we have to modify jUnit as well, because then by default `SLF4JQueryLoggingListener.class` won't be registered.

So by default we have to enable `SLF4JSlowQueryListener` and `SLF4JQueryLoggingListener` should be opt-in feature.

Is this understanding correct ?

File: spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/DataSourceProxyConfiguration.java (hunk 2 above)
Comment (beatfreaker) [reply spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/DataSourceProxyConfiguration.java:87]: Is this correct approach ? or we can have more optimal way to do it ?

Comment (marcingrzejszczak) [reply spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/DataSourceProxyConfiguration.java:87]: I said oops cause I've forgotten to add those lines :facepalm: Great that you caught it!

File: spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/TraceJdbcProperties.java (hunk 1 above)
Comment (marcingrzejszczak) [reply spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/TraceJdbcProperties.java:193]: I think that we want to set all the default additional loggings to `false` and make both opt in.

Comment (beatfreaker) [reply spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/TraceJdbcProperties.java:193]: Got it, will make all the `enableLogging=false` means no `QueryLogListener` or `SlowQueryLogListener` will be registered by default.

**Comment by marcingrzejszczak** [comment]
Lgtm - can we also mention that in the docs? Wdyt @gavlyukovskiy @jonatan-ivanov - are we not getting too defensive here with the opt in feature?

**Comment by jonatan-ivanov** [comment]
@marcingrzejszczak Although, I would love to see these details, I think the right call here is disable it by default:
1. It could have a performance impact (though I only measured this when Java 6-7 was the latest version)
2. It can have security implications (logging out PII data, sensitive data, secrets)

I think we could put an `INFO` message into the logs that lets the user know that this feature is turned off (maybe in the `afterPropertiesSet`/`@PostConstruct` of the ConfigProps bean?).

**Review by jonatan-ivanov — APPROVED** [review]

**Comment by marcingrzejszczak** [comment]
I don't think we should set ` message into the logs that lets the users know that this feature is turned off (maybe in the afterPropertiesSet/@PostConstruct of the ConfigProps bean?).` For example we don't do it with setting `RestTemplate` as a bean - we describe it in the docs. Maybe writing about this in the documentation is good enough?

**Review by marcingrzejszczak — CHANGES_REQUESTED** [review]
I'd update the documentation too with the property how to turn on the logging. Other than that LGTM

**Review by marcingrzejszczak — APPROVED** [review]

**Comment by marcingrzejszczak** [comment]
Great work @beatfreaker ! Thank you so much for your contribution!
